### ISSUE TITLE
录制自定义的glsurfaceview时，提示不支持

### ISSUE THREAD

**Issue by weichengzheng** [MobClub/ShareREC-for-Android#1]
not supported reason:

can not find GL renderer, maybe i am not in GL thread

 can not find GL version, maybe i am not in GL thread

GL version wrong: null

请问下这个是什么原因。

**Comment by alexyuyxj** [comment]
原因就是上面写的，你不是在GL线程里面调用REC，所以会有问题，请在doDrawFrame方法（或者与它通线程的方法）里面对REC进行操作
